<a href="https://colab.research.google.com/github/tej37/simplex/blob/main/simplexe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
v_d=input('le nombre de variable discret=')
print(v_d)

le nombre de variable discret=2
2


In [ ]:
def swap(tab,col1,col2):
  a=tab[col1]
  tab[col1]=tab[col2]
  tab[col2]=a
  return tab

In [ ]:
# prompt: make a swap function that swap two columns in a matrix

import numpy as np
def swap_columns(matrix, col1, col2):
  """
  Swaps two columns in a matrix.

  Args:
    matrix: The matrix to swap columns in.
    col1: The index of the first column to swap.
    col2: The index of the second column to swap.

  Returns:
    The matrix with the two columns swapped.
  """

  # Create a copy of the matrix
  new_matrix =matrix.copy()


  # Swap the two columns
  matrix[:,col1]=matrix[:,col2]
  matrix[:,col2]=new_matrix[:,col1]

  # Return the new matrix
  return matrix

# Example usage





In [ ]:
import numpy as np
import pandas as pd
A={'a1':[1, 2, 1],'a2':[1, 1, 0],'a3':[1,0,0],'a4':[0,1,0],'a5':[0,0,1]}
dA=pd.DataFrame(A)
A_ar=dA.values
C={'c1':[3],'c2':[2],'c3':[0],'c4':[0],'c5':[0]}
dC=pd.DataFrame(C)
C_ar=dC.values
b=np.array([80,100,40])
b=b.reshape(b.size,1)
print(b)
print(b.shape)
#b=b.reshape(b0)
print(A)

print(dA)

A_s=A_ar.shape
print(A_s)
dd=pd.DataFrame(A_ar)
print(dd)
print(dC)
print(C_ar.shape)
print(C_ar)
arr_swap=[]
X_res=[]
for i in range(A_s[1]):
  X_res.append(i)
print(X_res)
val="hh"

[[ 80]
 [100]
 [ 40]]
(3, 1)
{'a1': [1, 2, 1], 'a2': [1, 1, 0], 'a3': [1, 0, 0], 'a4': [0, 1, 0], 'a5': [0, 0, 1]}
   a1  a2  a3  a4  a5
0   1   1   1   0   0
1   2   1   0   1   0
2   1   0   0   0   1
(3, 5)
   0  1  2  3  4
0  1  1  1  0  0
1  2  1  0  1  0
2  1  0  0  0  1
   c1  c2  c3  c4  c5
0   3   2   0   0   0
(1, 5)
[[3 2 0 0 0]]
[0, 1, 2, 3, 4]


In [ ]:
import numpy as np
import pandas as pd
A={'a1':[-1, 1, 1],'a2':[4, -1, 1],'a3':[1,0,0],'a4':[0,1,0],'a5':[0,0,1]}
dA=pd.DataFrame(A)
A_ar=dA.values
C={'c1':[20],'c2':[60],'c3':[0],'c4':[0],'c5':[0]}
dC=pd.DataFrame(C)
C_ar=dC.values
b=np.array([60,30,80])
b=b.reshape(b.size,1)
print(b)
print(b.shape)
#b=b.reshape(b0)
print(A)

print(dA)

A_s=A_ar.shape
print(A_s)
dd=pd.DataFrame(A_ar)
print(dd)
print(dC)
print(C_ar.shape)
print(C_ar)
arr_swap=[]
X_res=[]
for i in range(A_s[1]):
  X_res.append(i)
print(X_res)
val="hh"

[[60]
 [30]
 [80]]
(3, 1)
{'a1': [-1, 1, 1], 'a2': [4, -1, 1], 'a3': [1, 0, 0], 'a4': [0, 1, 0], 'a5': [0, 0, 1]}
   a1  a2  a3  a4  a5
0  -1   4   1   0   0
1   1  -1   0   1   0
2   1   1   0   0   1
(3, 5)
   0  1  2  3  4
0 -1  4  1  0  0
1  1 -1  0  1  0
2  1  1  0  0  1
   c1  c2  c3  c4  c5
0  20  60   0   0   0
(1, 5)
[[20 60  0  0  0]]
[0, 1, 2, 3, 4]


In [ ]:
B=A_ar[:,A_s[1]-A_s[0]:]
print(B)
B_inv=np.linalg.inv(B)
xb=np.dot(B_inv,b)
print(xb)
print(xb.shape)
cb=C_ar[:,A_s[1]-A_s[0]:]
print(cb.shape)
print(cb)
X=[]
for i in range(A_s[1]-A_s[0]):
 X.append(0)
for i in range(cb.shape[1]):
  X.append(xb[i][0])
print(X)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[60.]
 [30.]
 [80.]]
(3, 1)
(1, 3)
[[0 0 0]]
[0, 0, 60.0, 30.0, 80.0]


etap1 yB=cb

In [ ]:
y=cb.dot(B_inv)
print(y.shape)
print(y)
assert y.shape==cb.shape ,'the shape mouch 9ad9ad'
print(A_ar[:,0].shape)

(1, 3)
[[ 8.  0. 28.]]
(3,)


etape 2 les deltat delta_i=ci-y*A_i
etape 3 les deltat_i>=0 sinon
etape 4 X_e prand l'index du max

In [ ]:
c_ar=C_ar.reshape(-1)
tej=np.array([44,33,55,66,77])


deltat=[]
it=A_s[1]-A_s[0]
nb=0
for i in range(it):
  deltat.append((c_ar[i])-(y.dot(A_ar[:,i])))
  if(deltat[i]<0):
     nb=nb+1
if(nb==it):
  print("finish")
  for i in range(0,len(arr_swap)-1,2):
    X_res=swap(X_res,arr_swap[i],arr_swap[i+1])
    print(X_res)
  for i in range(len(X_res)):
    print('X',X_res[i],'=',X[i])
else:
 X_e=deltat.index([max(deltat)])
 print(max(deltat))
 print(X_e)

finish
[4, 1, 2, 3, 0]
[0, 1, 2, 3, 4]
[4, 1, 2, 3, 0]
[0, 1, 2, 3, 4]
X 0 = 0
X 1 = 0
X 2 = 28.0
X 3 = 5.999999999999993
X 4 = 52.0


 etape5 B*alpha=A_e

In [ ]:
print(A_ar[:,X_e].shape)
print(B_inv.shape)
alpha=B_inv.dot(A_ar[:,X_e])
assert alpha.shape==A_ar[:,X_e].shape , 'the shape mouch 9ad9ad'
print(alpha)

(3,)
(3, 3)
[-0.25  0.75  1.25]


etape6 teta*

In [ ]:
tetaetoile=0
for i in range(A_s[0]):
 if (alpha[i]>0):
  mine=xb[i]/alpha[i]
for i in range(A_s[0]):
 if (alpha[i]>0):

  teta=xb[i]/alpha[i]
  if(teta<=mine):
    mine=teta
    tetaetoile=teta
    X_s=it+i

if(tetaetoile==0):
   print("la sol est non linaire")
else:
 # print(tetaetoile)
  print(X_s)


4


etape7 initialisation

In [ ]:
print(A_ar)
#A_ar[:,X_e],A_ar[:,X_s]=A_ar[:,X_s],A_ar[:,X_e]

print(A_ar)



[[-1  1  4  0  0]
 [ 1  0 -1  1  0]
 [ 1  0  1  0  1]]
[[-1  1  4  0  0]
 [ 1  0 -1  1  0]
 [ 1  0  1  0  1]]


In [ ]:
# Swap A
A_ar = swap_columns(A_ar, X_s, X_e)
print(A_ar)
# swap C
C_ar=swap_columns(C_ar, X_s, X_e)
print(C_ar)


[[ 0  1  4  0 -1]
 [ 0  0 -1  1  1]
 [ 1  0  1  0  1]]
[[ 0  0 60  0 20]]


In [ ]:
B=A_ar[:,A_s[1]-A_s[0]:]
print(B)
B_inv=np.linalg.inv(B)
xb=np.dot(B_inv,b)
print(xb)
print(xb.shape)
cb=C_ar[:,A_s[1]-A_s[0]:]
print(cb.shape)
print(cb)
X=[]
for i in range(A_s[1]-A_s[0]):
 X.append(0)
for i in range(cb.shape[1]):
  X.append(xb[i][0])
print(X)

[[ 4  0 -1]
 [-1  1  1]
 [ 1  0  1]]
[[28.]
 [ 6.]
 [52.]]
(3, 1)
(1, 3)
[[60  0 20]]
[0, 0, 28.0, 5.999999999999993, 52.0]


In [ ]:
arr_swap.append(X_e)
arr_swap.append(X_s)
print(arr_swap)

[1, 2, 0, 4, 0, 4, 0, 4]


In [ ]:
while(val!="finish"):
 print('2-3-4###################')
 c_ar=C_ar.reshape(-1)
 tej=np.array([44,33,55,66,77])


 deltat=[]
 it=A_s[1]-A_s[0]
 nb=0


 for i in range(it):
   deltat.append((c_ar[i])-(y.dot(A_ar[:,i])))
   if(deltat[i]<0):
      nb=nb+1
 if(nb==it):
   val="finish"
   print("finish")
   for i in range(0,len(arr_swap)-1,2):
     X_res=swap(X_res,arr_swap[i],arr_swap[i+1])
     print(X_res)
   for i in range(len(X_res)):
     print('X',X_res[i],'=',X[i])
 else:
  X_e=deltat.index([max(deltat)])
  print(max(deltat))
  print(X_e)
  print('5-##########################')
  print(A_ar[:,X_e].shape)
  print(B_inv.shape)
  alpha=B_inv.dot(A_ar[:,X_e])
  assert alpha.shape==A_ar[:,X_e].shape , 'the shape mouch 9ad9ad'
  print(alpha)
  print('6-####################')
  tetaetoile=0
  for i in range(A_s[0]):
   if (alpha[i]>0):
    mine=xb[i]/alpha[i]
  for i in range(A_s[0]):
   if (alpha[i]>0):

    teta=xb[i]/alpha[i]
    if(teta<=mine):
      mine=teta
      tetaetoile=teta
      X_s=it+i

  if(tetaetoile==0):
     print("la sol est non linaire")
  else:
   # print(tetaetoile)
    print(X_s)
  print('7-##################')
  # Swap A
  A_ar = swap_columns(A_ar, X_s, X_e)
  print(A_ar)
  # swap C
  C_ar=swap_columns(C_ar, X_s, X_e)
  print(C_ar)
  print('7-#######################')
  B=A_ar[:,A_s[1]-A_s[0]:]
  print(B)
  B_inv=np.linalg.inv(B)
  xb=np.dot(B_inv,b)
  print(xb)
  print(xb.shape)
  cb=C_ar[:,A_s[1]-A_s[0]:]
  print(cb.shape)
  print(cb)
  X=[]
  for i in range(A_s[1]-A_s[0]):
   X.append(0)
  for i in range(cb.shape[1]):
   X.append(xb[i][0])
  print(X)
  print('swap-###########################')
  arr_swap.append(X_e)
  arr_swap.append(X_s)
  print(arr_swap)
  print('1-###############################')
  y=cb.dot(B_inv)
  print(y.shape)
  print(y)
  assert y.shape==cb.shape ,'the shape mouch 9ad9ad'
  print(A_ar[:,0].shape)


2-3-4###################
[60.]
1
5-##########################
(3,)
(3, 3)
[ 4. -1.  1.]
6-####################
2
7-##################
[[-1  1  4  0  0]
 [ 1  0 -1  1  0]
 [ 1  0  1  0  1]]
[[20  0 60  0  0]]
7-#######################
[[ 4  0  0]
 [-1  1  0]
 [ 1  0  1]]
[[15.]
 [45.]
 [65.]]
(3, 1)
(1, 3)
[[60  0  0]]
[0, 0, 15.0, 45.0, 65.0]
swap-###########################
[1, 2]
1-###############################
(1, 3)
[[15.  0.  0.]]
(3,)
2-3-4###################
[35.]
0
5-##########################
(3,)
(3, 3)
[-0.25  0.75  1.25]
6-####################
4
7-##################
[[ 0  1  4  0 -1]
 [ 0  0 -1  1  1]
 [ 1  0  1  0  1]]
[[ 0  0 60  0 20]]
7-#######################
[[ 4  0 -1]
 [-1  1  1]
 [ 1  0  1]]
[[28.]
 [ 6.]
 [52.]]
(3, 1)
(1, 3)
[[60  0 20]]
[0, 0, 28.0, 5.999999999999993, 52.0]
swap-###########################
[1, 2, 0, 4]
1-###############################
(1, 3)
[[ 8.  0. 28.]]
(3,)
2-3-4###################
finish
[0, 2, 1, 3, 4]
[4, 2, 1, 3, 0]
X 4 = 0
X 2 = 0
X